name: Build and Deploy

on: push

permissions:
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          pip install openpyxl python-docx

      - name: Download source data
        run: |
          for f in devices spectrum; do
            wget -q https://github.com/${{ github.repository }}/releases/download/data/$f.7z
            p7zip -d $f.7z
          done
          mv devices.xlsx.csv ref.devices.xlsx.csv
          mv spectrum.docx.csv ref.spectrum.docx.csv

      - name: Build device list
        run: |
          ./build.py

      - name: Post build checks
        run: |
          [ -f dist/devices.js ] || exit 1
          [ -f dist/spectrum.js ] || exit 1
          diff -u ref.devices.xlsx.csv devices.xlsx.csv
          diff -u ref.spectrum.docx.csv spectrum.docx.csv
          git status

      - name: Upload site files as artifact
        if: github.ref_name == 'main'
        id: deployment
        uses: actions/upload-pages-artifact@v3
        with:
          path: dist/

  deploy:
    if: github.ref_name == 'main'
    runs-on: ubuntu-24.04
    needs: build
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
